### ISSUE TITLE
func_door doesn't render properly

### ISSUE THREAD

**Issue by ethan101au** [Msalinas2877/Source2013Engine#1]
func_door sometimes fails to render at all or sometimes it will render strangely. These screenshots were taken in **windowed mode** on **DirectX 9** with a **nVidia GTX 1070**.

No Render: The first func_door was spotted with nothing but a **trigger** in-front of it, this resulted in the func_door being **completely invisible**. Image: https://media.discordapp.net/attachments/367991955185074176/498379333422022657/unknown.png?width=1605&height=904

Strange Render: The second func_door was engulfed in a **skip brush** (only on the right side of the door), this func_door also had a thin door-sized **areaportal** hiding inside the func_door brush. There is a **clip brush** the size of the door behind it. Image: https://media.discordapp.net/attachments/367991955185074176/498379844716068864/unknown.png?width=1609&height=904

**Comment by Msalinas2877** [comment]
After taking a look seems like this affects all brush based entities, as the function DrawBrushModelEx() is incomplete in View.cpp, in 2007 the function DrawBrushModel() was being used instead

**Comment by ethan101au** [comment]
Should probably close this issue now.

**Comment by Msalinas2877** [comment]
21cb254da827b612bd9d4659926e248eb893e5b2
