### ISSUE TITLE
Sounds play consistently after they are played at least once

### ISSUE THREAD

**Issue by ethan101au** [Msalinas2877/Source2013Engine#2]
If a **VPhysics prop** or the Player (the Player is classified as a **QPhysics prop**, does not apply to NPCs) physically touches another **VPhysics prop** it will play **continuous collision noises**.

Side note: When **VPhysics props** touches any **QPhysics prop** (NPCs included) **with an impact** it plays the **prop impact sound** (It shouldn't do this).

**Update: This may be an all-around bug that causes any (loopable?) sound to continuously play, I have experienced this when riding the Jeep. The driving sounds keep playing even if I stop moving, or exit the vehicle. I have also experienced this when Antlions initially fly, the flight/jump sound plays but continues playing even after they are done jumping.**

**Comment by Msalinas2877** [comment]
d7f26e10d584fccbd29c0856b14ceda837dcddbf
