### ISSUE TITLE
cl_predict 1 creates jagged movement

### ISSUE THREAD

**Issue by ethan101au** [Msalinas2877/Source2013Engine#3]
If cl_predict 1 is set the Player's movement becomes jagged and the **initial tap** of a movement key is **delayed slightly**, if the player **continues to move** the **movement is inconsistent** and **not smooth**, when the Player **stops moving** they **rubber-band backwards** a little bit.

**Comment by Msalinas2877** [comment]
This seems to happen too in retail Half-Life 2 when set to 1, that means prediction is not being turned off for some reason, i´ll take a look

**Comment by Msalinas2877** [comment]
78b52cbd060e1f0f0834d65ea2e1a2058dc4069d
